# Standards: 0.11
---

# 1.6.1.3 Ensure SELinux policy is configured (Scored)

- name: 1.6.1.3 Ensure SELinux policy is configured (Scored)
  selinux:
    policy: targeted
    state: enforcing
  tags:
      - level-2
      - section-1
      - "1.6.1.3"
      - scored