# Standards: 0.11
---

# 4.1.3 Ensure auditing for processes that start prior to auditd is enabled

- name: 4.1.3 - Check if grub default exist
  stat:
    path: "{{ cis_grub_default_filename }}"
  register: grub_default_4_1_3
  tags:
    - level-2
    - section-4
    - "4.1.3"
    - scored
- name: 4.1.3 - Ensure auditing for processes that start prior to auditd is enabled
  lineinfile:
    dest: "{{ cis_grub_default_filename }}"
    regexp: "^GRUB_CMDLINE_LINUX="
    line: 'GRUB_CMDLINE_LINUX="audit=1"'
  when: grub_default_4_1_3.stat.exists is defined and grub_default_4_1_3.stat.exists
  tags:
    - level-2
    - section-4
    - "4.1.3"
    - scored
- name: 4.1.3 - Ensure auditing for processes that start prior to auditd is enabled
  shell: "grub2-mkconfig -o /boot/grub2/grub.cfg"
  tags:
    - level-2
    - section-4
    - "4.1.3"
    - scored