# Standards: 0.11
---

# 4.1.17 Ensure kernel module loading and unloading is collected

- name: 4.1.17 Ensure kernel module loading and unloading is collected
  shell: "grep access {{ cis_audit_rules_filename }}"
  register: access
  changed_when: False
  ignore_errors: true
  tags:
    - "4.1.11"
    - level-2
    - section-4
    - scored


- name: 4.1.17 Ensure kernel module loading and unloading is collected
  lineinfile:
    dest: "{{ cis_audit_rules_filename }}"
    line: "{{ item }}"
  with_items:
    - '# 4.1.17 Ensure kernel module loading and unloading is collected'
    - '-w /sbin/insmod -p x -k modules'
    - '-w /sbin/rmmod -p x -k modules'
    - '-w /sbin/modprobe -p x -k modules'
    - '-a always,exit -F arch=b64 -S init_module -S delete_module -k modules'

  tags:
    - "4.1.17"
    - level-2
    - section-4
    - scored