# Standards: 0.11
---

# 5.2.6 - Ensure SSH X11 forwarding is disabled

- include: stat_sshd_config.yml
  tags:
    - level-2
    - section-5
    - "5.2.6"
    - scored

- name: 5.2.4 - Ensure SSH X11 forwarding is disabled
  lineinfile:
    regexp: "^X11Forwarding\\s+"
    line: "X11Forwarding no"
    dest: "/etc/ssh/sshd_config"
  when: sshd_config.stat.exists
  notify:
    - Restart sshd
  tags:
    - level-2
    - section-5
    - "5.2.6"
    - scored