# Standards: 0.11
---

# 1.4.2 - Ensure authentication is required for single user mode

- name: 1.4.2 - Check if rescue.service file exists
  stat:
    path: "{{ cis_rescue_service_filename }}"
  register: rescue_service_1_4_2
  tags:
    - level-1
    - "1.4.2"
    - scored

- name: 1.4.2 - Ensure authentication is required for single-user mode
  copy:
    dest: "{{ cis_rescue_service_filename }}"
    content: "ExecStart=-/bin/sh -c \"/sbin/sulogin; /usr/bin/systemctl --fail --no-block default\" \n"
  when: rescue_service_1_4_2.stat.exists is not defined or not rescue_service_1_4_2.stat.exists
  tags:
    - level-1
    - "1.4.2"
    - scored

- name: 1.4.2 - Ensure authentication is required for single-user mode
  lineinfile:
    dest: "{{ cis_rescue_service_filename }}"
    regexp: "^ExecStart="
    line: "ExecStart=-/bin/sh -c \"/sbin/sulogin; /usr/bin/systemctl --fail --no-block default\""
  when: rescue_service_1_4_2.stat.exists is defined and rescue_service_1_4_2.stat.exists
  tags:
    - level-1
    - "1.4.2"
    - scored

- name: 1.4.2 - Check if emergency.service file exists
  stat:
    path: "{{ cis_emergency_service_filename }}"
  register: emergency_service_1_4_2
  tags:
    - level-1
    - "1.4.2"
    - scored

- name: 1.4.2 - Ensure authentication is required for single-user mode
  copy:
    dest: "{{ cis_emergency_service_filename }}"
    content: "ExecStart=-/bin/sh -c \"/sbin/sulogin; /usr/bin/systemctl --fail --no-block default\" \n"
  when: emergency_service_1_4_2.stat.exists is not defined or not emergency_service_1_4_2.stat.exists
  tags:
    - level-1
    - "1.4.2"
    - scored

- name: 1.4.2 - Ensure authentication is required for single-user mode
  lineinfile:
    dest: "{{ cis_emergency_service_filename }}"
    regexp: "^ExecStart="
    line: "ExecStart=-/bin/sh -c \"/sbin/sulogin; /usr/bin/systemctl --fail --no-block default\""
  when: emergency_service_1_4_2.stat.exists is defined and emergency_service_1_4_2.stat.exists
  tags:
    - level-1
    - "1.4.2"
    - scored