# Standards: 0.11
---

# 2.1.8 Ensure DNS Server is not enabled

- name: 2.1.8 - Ensure DNS Server is not enabled
  systemd:
    name: "named"
    enabled: no
    state: stopped
  ignore_errors: True
  tags:
    - level-1
    - "2.1.8"
    - scored
