# Standards: 0.11
---

# 2.1.12 Ensure Samba is not enabled

- name: 2.1.12 - Ensure Samba is not enabled
  systemd:
    name: "smb"
    enabled: no
    state: stopped
  ignore_errors: True
  tags:
    - level-1
    - "2.1.12"
    - scored
