# Standards: 0.11
---

# 2.1.16 Ensure NIS Server is not enabled

- name: 2.1.16 - Ensure NIS Server is not enabled
  systemd:
    name: "ypserv"
    enabled: no
    state: stopped
  ignore_errors: True
  tags:
    - level-1
    - "2.1.16"
    - scored
