# Standards: 0.11
---

# 2.1.9 Ensure FTP Server is not enabled

- name: 2.1.9 - Ensure FTP Server is not enabled
  systemd:
    name: "vsftpd"
    enabled: no
    state: stopped
  ignore_errors: True
  tags:
    - level-1
    - "2.1.9"
    - scored
