# Standards: 0.11
---

# 2.1.3 Ensure Avahi Server is not enabled 

- name: 2.1.3 - Ensure Avahi Server is not enabled
  systemd:
    name: "avahi-daemon"
    enabled: no
    state: stopped
  ignore_errors: True
  tags:
    - level-1
    - "2.1.3"
    - scored