# Standards: 0.11
---

# 2.1.14 Ensure SNMP Server is not enabled

- name: 2.1.14 - Ensure SNMP Server is not enabled
  systemd:
    name: "snmpd"
    enabled: no
    state: stopped
  ignore_errors: True
  tags:
    - level-1
    - "2.1.14"
    - scored
