# Standards: 0.11
---

# 3.2.9 Ensure IPv6 router advertisements are not accepted 

- name: 3.2.9 - Ensure IPv6 router advertisements are not accepted  
  sysctl:
    name: net.ipv6.conf.all.accept_ra
    value: 0
    state: present
  tags:
    - level-1
    - section-3
    - "3.2.9"
    - scored

- name: 3.2.9 - Ensure IPv6 router advertisements are not accepted  
  sysctl:
    name: net.ipv6.conf.default.accept_ra
    value: 0
    state: present
  tags:
    - level-1
    - section-3
    - "3.2.9"
    - scored


- name: 3.2.9 - Ensure IPv6 router advertisements are not accepted in active kernel parameters
  command: "{{ item }}"
  with_items:
    - "sysctl -w net.ipv6.conf.all.accept_ra=0"
    - "sysctl -w net.ipv6.conf.default.accept_ra=0"
    - "sysctl -w net.ipv4.route.flush=1"
  tags:
    - level-1
    - section-3
    - "3.2.9"
    - scored
