# Standards: 0.11
---

# 5.2.14 Ensure only strong MAC algorithms are used 

- name: 5.2.14 - Check if /etc/ssh/sshd_config exists
  stat:
    path: /etc/ssh/sshd_config
  register: sshd_config_5_2_14
  tags:
    - level-1
    - section-5
    - "5.2.14"
    - scored

- name: 5.2.14 - Ensure only approved MAC algorithms are used
  lineinfile:
    regexp: "^MACs\\s+"
    line: "MACs {{ cis_sshd_macs }}"
    dest: "/etc/ssh/sshd_config"
  when: sshd_config_5_2_14.stat.exists
  notify:
    - Restart sshd
  tags:
    - level-1
    - section-5
    - "5.2.14"
    - scored