# Standards: 0.11
---

# 5.2.7 Ensure SSH MaxAuthTries is set to 4 or less 

- name: 5.2.7 - Check if /etc/ssh/sshd_config exists
  stat:
    path: /etc/ssh/sshd_config
  register: sshd_config_5_2_7
  tags:
    - level-1
    - section-5
    - "5.2.7"
    - scored

- name: 5.2.7 - Ensure SSH MaxAuthTries is set to 4 or less
  lineinfile:
    regexp: "^MaxAuthTries\\s+"
    line: "MaxAuthTries {{ cis_sshd_max_auth_tries }}"
    dest: "/etc/ssh/sshd_config"
  when: sshd_config_5_2_7.stat.exists
  notify:
    - Restart sshd
  tags:
    - level-1
    - section-5
    - "5.2.7"
    - scored