# Standards: 0.11
---

# 5.2.12 Ensure SSH PermitUserEnvironment is disabled

- name: 5.2.12 - Check if /etc/ssh/sshd_config exists
  stat:
    path: /etc/ssh/sshd_config
  register: sshd_config_5_2_12
  tags:
    - level-1
    - section-5
    - "5.2.12"
    - scored

- name: 5.2.12 - Ensure SSH PermitUserEnvironment is disabled
  lineinfile:
    regexp: "^PermitUserEnvironment\\s+"
    line: "PermitUserEnvironment no"
    dest: "/etc/ssh/sshd_config"
  when: sshd_config_5_2_12.stat.exists
  notify:
    - Restart sshd
  tags:
    - level-1
    - section-5
    - "5.2.12"
    - scored