# Standards: 0.11
---

# 5.2.10 Ensure SSH root login is disabled

- name: 5.2.10 - Check if /etc/ssh/sshd_config exists
  stat:
    path: /etc/ssh/sshd_config
  register: sshd_config_5_2_10
  tags:
    - level-1
    - section-5
    - "5.2.10"
    - scored

- name: 5.2.10 - Ensure SSH root login is disabled
  lineinfile:
    regexp: "^PermitRootLogin\\s+"
    line: "PermitRootLogin no"
    dest: "/etc/ssh/sshd_config"
  when: sshd_config_5_2_10.stat.exists
  notify:
    - Restart sshd
  tags:
    - level-1
    - section-5
    - "5.2.10"
    - scored