# Standards: 0.11
---

# 5.2.11 Ensure SSH PermitEmptyPasswords is disabled

- name: 5.2.11 - Check if /etc/ssh/sshd_config exists
  stat:
    path: /etc/ssh/sshd_config
  register: sshd_config_5_2_11
  tags:
    - level-1
    - section-5
    - "5.2.11"
    - scored

- name: 5.2.11 - Ensure SSH PermitEmptyPasswords is disabled
  lineinfile:
    regexp: "^PermitEmptyPasswords\\s+"
    line: "PermitEmptyPasswords no"
    dest: "/etc/ssh/sshd_config"
  when: sshd_config_5_2_11.stat.exists
  notify:
    - Restart sshd
  tags:
    - level-1
    - section-5
    - "5.2.11"
    - scored