# Standards: 0.11
---

# 5.2.17 Ensure SSH LoginGraceTime is set to one minute or less   

- name: 5.2.17 - Check if /etc/ssh/sshd_config exists
  stat:
    path: /etc/ssh/sshd_config
  register: sshd_config_5_2_17
  tags:
    - level-1
    - section-5
    - "5.2.17"
    - scored

- name: 5.2.17 - Ensure SSH LoginGraceTime is set to one minute or less
  lineinfile:
    regexp: "^LoginGraceTime\\s+"
    line: "LoginGraceTime {{ cis_sshd_login_grace_time }}"
    dest: "/etc/ssh/sshd_config"
  when: sshd_config_5_2_17.stat.exists
  notify:
    - Restart sshd
  tags:
    - level-1
    - section-5
    - "5.2.17"
    - scored