# Standards: 0.11
---

# 5.2.4 - Ensure SSH Protocol is set to 2

- name: 5.2.4 - Check if /etc/ssh/sshd_config exists
  stat:
    path: /etc/ssh/sshd_config
  register: sshd_config_5_2_4
  tags:
    - level-1
    - section-5
    - "5.2.4"
    - scored

- name: 5.2.4 - Ensure SSH Protocol is set to 2
  lineinfile:
    regexp: "^Protocol\\s+"
    line: "Protocol 2"
    dest: "/etc/ssh/sshd_config"
  notify: "Restart sshd"
  when: sshd_config_5_2_4.stat.exists
  tags:
    - level-1
    - section-5
    - "5.2.4"
    - scored