# Standards: 0.11
---

# 5.2.8 Ensure SSH IgnoreRhosts is enabled 

- name: 5.2.8 - Check if /etc/ssh/sshd_config exists
  stat:
    path: /etc/ssh/sshd_config
  register: sshd_config_5_2_8
  tags:
    - level-1
    - section-5
    - "5.2.7"
    - scored

- name: 5.2.8 - Ensure SSH IgnoreRhosts is enabled
  lineinfile:
    regexp: "^IgnoreRhosts\\s+"
    line: "IgnoreRhosts yes"
    dest: "/etc/ssh/sshd_config"
  when: sshd_config_5_2_8.stat.exists
  notify:
    - Restart sshd
  tags:
    - level-1
    - section-5
    - "5.2.8"
    - scored